version: "2"

services:
   tomcat:
      volumes:
       - ./tomcat/logs:/usr/local/tomcat/logs
      expose:
       - 8009
      image: walesyu/tomcat
      container_name: "tomcat"
      build: ./tomcat
      environment:
       - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom
      networks:
        tomcat_net:
          ipv4_address: 192.168.100.2
   http:
      volumes:
       - ./httpd/logs:/var/log/apache2
      ports:
       - "80:80"
       - "443:443"
      image: walesyu/httpd
      container_name: "httpd"
      build: ./httpd
      networks:
        tomcat_net:
          ipv4_address: 192.168.100.3
networks:
    tomcat_net:
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: 192.168.100.0/24